export const EventType = Object.freeze({
  BOOKING_CREATED: 'BOOKING_CREATED',
  BOOKING_CONFIRMED: 'BOOKING_CONFIRMED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_AUTO_CANCELLED: 'BOOKING_AUTO_CANCELLED',
  ROOM_CREATED: 'ROOM_CREATED',
  ROOM_UPDATED: 'ROOM_UPDATED',
  ROOM_DEACTIVATED: 'ROOM_DEACTIVATED',
  USER_CREATED: 'USER_CREATED',
  USER_BLOCKED: 'USER_BLOCKED',
  USER_UNBLOCKED: 'USER_UNBLOCKED',
});
